apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-code"
  labels:
    app: "{{ .Values.appName }}-code"
spec:
  type: ClusterIP
  ports:
    - port: { { .Values.code.servicePort } }
      targetPort: { { .Values.code.containerPort } }
      protocol: TCP
      name: http
  selector:
    app: "{{ .Values.appName }}-code"
